### ISSUE TITLE
Регулярные встречи сообществ

### ISSUE THREAD

**Issue by Realetive** [in100gramm/events#5]
Есть идея организации регулярных встреч как это уже делают ребята с [ngУжином](https://github.com/in100gramm/events/blob/master/events/_recurrence/ng%D0%A3%D0%B6%D0%B8%D0%BD.md) — в идеале, чтобы каждый будний день имел какую-то тематическую привязку к сообществу. Сообществ много, нужен хотя бы один куратор на каждую встречу для коллаборации формата (дринкап / лайт-толк / «круглый стол» и т. д.) и требований (телевизор / монитор / проектор и т. д.), [барного ассортимента](https://github.com/in100gramm/menu).

Если у вас нет профиля на GitHub, пишите в
- Twitter: https://twitter.com/Realetive/status/1181997675409002498
- Telegram: https://t.me/in100gramm_bar / tg://resolve?domain=in100gramm_bar

## Сообщества

- [ ] React — [обсуждение](https://github.com/in100gramm/events/issues/6)
- [x] Angular — [ngУжин](https://github.com/in100gramm/events/blob/master/events/_recurrence/ng%D0%A3%D0%B6%D0%B8%D0%BD.md)
- [ ] Vue — [обсуждение](https://github.com/in100gramm/events/issues/7)
- [ ] Svelte — [обсуждение](https://github.com/in100gramm/events/issues/8)
- [ ] BeerJS
- [x] Вёрстка и a11y — [обсуждение](https://github.com/in100gramm/events/issues/9)
- [ ] IT-стендапы — [обсуждение](https://github.com/in100gramm/events/issues/10)
- [ ] GameDev — [обсуждение](https://github.com/in100gramm/events/issues/11)
- [ ] DevOps — [обсуждение](https://github.com/in100gramm/events/issues/12)
- [ ] Pet-проекты — [обсуждение](https://github.com/in100gramm/events/issues/13)
- [ ] HR (head recruiting) — [обсуждение](https://github.com/in100gramm/events/issues/14)
- [ ] Python — [обсуждение](https://github.com/in100gramm/events/issues/16)
- [ ] BigData и Data Engineering — [обсуждение](https://github.com/in100gramm/events/issues/17)
- [ ] PM (менеджеры проектов)
- [ ] Team lead (руководители команд и тех. руководители)
- [ ] Дизайн / UX & UI / когнитивная психология
- [ ] SMM
- [ ] JavaScript / NodeJS
- [ ] PHP
- [ ] Golang
- [ ] FProg (функциональное программирование)
- [ ] Java
- [ ] ???

Тем для обсуждения очень много — от насущных проблем на текущем проекте до _computer science_ в самом широком смысле этого слова. Делиться опытом крайне важно — это помогает снизить ощущение «выгорания», вызванного замкнутостью круга общения.

**Comment by Realetive** [comment]
- [ ] React — [обсуждение](https://github.com/in100gramm/events/issues/6)

**Comment by Realetive** [comment]
- [ ] Vue — [обсуждение](https://github.com/in100gramm/events/issues/7)

**Comment by Realetive** [comment]
- [ ] Svelte — [обсуждение](https://github.com/in100gramm/events/issues/8)

**Comment by Realetive** [comment]
- [x] Вёрстка и a11y — [обсуждение](https://github.com/in100gramm/events/issues/9)

**Comment by Realetive** [comment]
- [ ] IT-стендапы — [обсуждение](https://github.com/in100gramm/events/issues/10)

**Comment by Realetive** [comment]
- [ ] GameDev — [обсуждение](https://github.com/in100gramm/events/issues/11)

**Comment by Realetive** [comment]
- [ ] DevOps — [обсуждение](https://github.com/in100gramm/events/issues/12)

**Comment by Realetive** [comment]
- [ ] Pet-проекты — [обсуждение](https://github.com/in100gramm/events/issues/13)

**Comment by Realetive** [comment]
- [ ] HR (head recruiting) — [обсуждение](https://github.com/in100gramm/events/issues/14)

**Comment by Realetive** [comment]
- [ ] Python — [обсуждение](https://github.com/in100gramm/events/issues/16)

**Comment by Realetive** [comment]
- [ ] BigData и Data Engineering — [обсуждение](https://github.com/in100gramm/events/issues/17)
